# Generated by Django 3.2.12 on 2022-03-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=20, unique=True)),
                ('max_voltage', models.FloatField(default=0.0)),
                ('min_voltage', models.FloatField(default=0.0)),
                ('total_voltage', models.FloatField(default=0.0)),
                ('max_current', models.FloatField(default=0.0)),
                ('min_current', models.FloatField(default=0.0)),
                ('soc', models.FloatField(default=0.0)),
                ('max_temperature', models.FloatField(default=0.0)),
                ('min_temperature', models.FloatField(default=0.0)),
                ('battery_num', models.IntegerField(default=0)),
            ],
        ),
    ]
