# Generated by Django 3.2.12 on 2022-03-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('cell_1', models.FloatField(default=12.6)),
                ('cell_2', models.FloatField(default=12.6)),
                ('cell_3', models.FloatField(default=12.6)),
                ('cell_4', models.FloatField(default=12.6)),
                ('cell_5', models.FloatField(default=12.6)),
                ('cell_6', models.FloatField(default=12.6)),
                ('cell_7', models.FloatField(default=12.6)),
                ('cell_8', models.FloatField(default=12.6)),
                ('cell_9', models.FloatField(default=12.6)),
                ('cell_10', models.FloatField(default=12.6)),
                ('cell_11', models.FloatField(default=12.6)),
                ('cell_12', models.FloatField(default=12.6)),
                ('cell_13', models.FloatField(default=12.6)),
                ('cell_14', models.FloatField(default=12.6)),
                ('cell_15', models.FloatField(default=12.6)),
                ('cell_16', models.FloatField(default=12.6)),
                ('cell_17', models.FloatField(default=12.6)),
                ('cell_18', models.FloatField(default=12.6)),
                ('cell_19', models.FloatField(default=12.6)),
                ('cell_20', models.FloatField(default=12.6)),
                ('cell_21', models.FloatField(default=12.6)),
                ('cell_22', models.FloatField(default=12.6)),
                ('cell_23', models.FloatField(default=12.6)),
                ('cell_24', models.FloatField(default=12.6)),
                ('max_cell_tem', models.FloatField(default=25.4)),
                ('min_cell_tem', models.FloatField(default=2.5)),
                ('max_cell_vol', models.FloatField(default=3.3)),
                ('min_cell_vol', models.FloatField(default=2.4)),
                ('max_cell_cur', models.FloatField(default=0.5)),
                ('min_cell_cur', models.FloatField(default=0.2)),
                ('cell_soc', models.FloatField(default=22.6)),
                ('cell_soh', models.FloatField(default=0.963)),
            ],
        ),
    ]
