# Generated by Django 3.2.12 on 2022-03-06 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_battery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Battery',
            new_name='Battery1',
        ),
    ]
