# Generated by Django 3.2.12 on 2022-03-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20220306_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='battery_id',
            field=models.IntegerField(),
        ),
    ]
