# Generated by Django 3.2.12 on 2022-03-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_battery_battery_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime1', models.CharField(max_length=20)),
                ('datetime2', models.CharField(max_length=20)),
                ('msg', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime1', models.CharField(max_length=20)),
                ('abstract', models.CharField(max_length=50)),
                ('details', models.TextField(default='')),
            ],
        ),
    ]
